---
title: Proyecto integrador
---

## Objetivo {.unnumbered}
Integrar los temas del curso en un proyecto final.

## Introducción
Durante el curso se estudiaron fundamentos para el análisis de algoritmos, y algoritmos para resolver diferentes tipos de problemas, como ordenamiento, búsqueda, codificación de conjuntos, e intersecciones de conjuntos. Todos estos temas se articulan en la construcción de índice invertido, que permite realizar búsquedas eficientes en colecciones. Puede ser utilizado para realizar análisis de grandes colecciones de datos no estructurados, y en particular, de documentos. Su uso puede ir desde análisis exploratorio, es decir, un análisis cuyo objetivo es ayudar al científico de datos a conocer y descubrir características de la colección, así como para realizar clasificación automática si se utiliza una colección etiquetada.
 

<iframe width="560" height="315" src="https://www.youtube.com/embed/lndPZk95jeE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Actividad [con reporte]


Instrucciones:


En un notebook de Jupyter construye un índice invertido a partir de una de las colecciones provistas.

Diseña un algoritmo para resolver consultas conjuntivas (terminoA & termino B & ...) utilizando el algoritmo de intersección de su elección (recuerde que debe explicar porque eligió ese algoritmo en particular).

Crea una celda en el notebook donde se construya el índice invertido (no importa que se definan las funciones necesarias en otras celdas). Use cualquiera de los conjuntos de datos que hemos usado en el curso o incluso el emo50k.json.gz que se explica en el video.

Integra otra celda en el notebook para realizar las consultas (no importa que se definan las funciones necesarias en otras celdas)

Realiza una revisión de los algoritmos vistos en el curso, repasa los experimentos y comparaciones en cada tema, discuta los resultados de cada tema.

Tu reporte de  actividad debe incluir:

- Tu nombre
- Introducción a los índices invertidos
- Resume
- Explicación de cada tema y discusión de los resultados experimentales.
- Descripción de su índice invertido y de como funcionan las celdas para construcción y consulta
- Conclusiones
- Referencias

Entrega tu actividad  en formato Notebook de Jupyter y el PDF del mismo Notebook. 



